/* Crenova MS8233D reader: Stage 3 self-hosted Wi-Fi dashboard.
 * Acquisition timing and COM profile are retained from accepted Stage 1.
 * The browser receives normalized states only -- never SEG/COM cells.
 */
#include <Arduino.h>
#include <WiFi.h>
#include <ESPmDNS.h>
#include <esp_http_server.h>
#include "secrets.h"

constexpr int COM_PIN=D0, SEG_PIN=D1, PROBE_PIN=D2;
constexpr int ADDR[4]={D3,D6,D7,D8}; constexpr int N=15;
constexpr uint8_t EXPECTED[8]={0,3,2,1,2,1,2,1};
constexpr uint8_t COMS[4][8]={{0,3,2,1,2,1,2,1},{2,1,0,3,2,1,2,1},{2,1,2,1,0,3,2,1},{2,1,2,1,2,1,0,3}};
float centers[4], tolerance[4]; uint32_t hist[256], calId=0,seq=0,lastStatus=0; bool calibrated=false;
const char *errorReason="none"; int errorPhase=-1;
struct Edge{uint32_t lo,hi;int mv;}; struct Frame{Edge edge[9];uint32_t begin[8],end[8],post[8];uint16_t mv[8][N],com[8];} f;

httpd_handle_t server=nullptr; int wsClients[4]={-1,-1,-1,-1};
String lastPublished, candidate; uint8_t candidateCount=0; String lastStateJson="{\"status\":\"starting\"}";

const char PAGE[] PROGMEM=R"HTML(<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>MS8233D</title><style>
*{box-sizing:border-box}body{margin:0;background:#0d1210;color:#e6f4eb;font:16px system-ui,sans-serif}.panel{max-width:900px;margin:auto;min-height:100vh;padding:18px 20px}
header{display:flex;justify-content:space-between;align-items:center;letter-spacing:.12em;color:#8fa898;font-size:.75rem}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:#7e8b82;margin-right:6px}.on{background:#59db86;box-shadow:0 0 10px #59db86}
.lcd{margin:6vh 0 1rem;padding:1.2rem 1rem 1rem;border:1px solid #26362d;border-radius:14px;background:#111a15}
.tags{display:flex;gap:.5rem;min-height:1.6rem;flex-wrap:wrap}.tags.fn{justify-content:center;border-top:1px solid #1f2d25;padding-top:.8rem}.sep{width:1.2rem}.tag{font-size:.85rem;font-weight:600;letter-spacing:.08em;color:#33453a;padding:.15rem .55rem;border-radius:6px}.tag.on{color:#0d1210;background:#7ee39b}.tag.warn.on{background:#f0c85a}
.read{display:flex;align-items:baseline;justify-content:center;gap:.6rem;margin:1.5rem 0 1rem;flex-wrap:nowrap}.number{font:clamp(3.6rem,16vw,9rem) ui-monospace,monospace;letter-spacing:-.06em;line-height:1;color:#d8ffd6;white-space:nowrap}.number.ol{color:#f0c85a}.number.stale{opacity:.35}
.unit{font-size:clamp(1.6rem,6vw,3.6rem);color:#7ee39b;min-width:2.2em;white-space:nowrap}.unit.q{color:#5f7268;font-size:1.1rem}
.chart{position:relative;height:150px;margin-top:1.4rem;padding:8px 0 20px 64px}.chart svg{width:100%;height:100%;display:block;border-left:1px solid #2c3f33;border-bottom:1px solid #2c3f33}.chart polyline{fill:none;stroke:#64db8b;stroke-width:1.5;vector-effect:non-scaling-stroke;stroke-linejoin:round}
.stats{display:flex;gap:1rem;justify-content:space-between;margin-top:1rem;color:#829087;font-size:.7rem;letter-spacing:.1em}.stats b{display:block;color:#d8ffd6;font:1.1rem ui-monospace,monospace;letter-spacing:0;margin-top:.2rem}.y{white-space:nowrap;position:absolute;left:0;width:58px;text-align:right;color:#829087;font-size:.7rem}.y.t{top:4px}.y.b{bottom:16px}.x{position:absolute;left:64px;right:0;bottom:0;display:flex;justify-content:space-between;color:#829087;font-size:.7rem}
</style></head><body><main class=panel><header><span>CRENOVA · MS8233D</span><span><i id=dot class=dot></i><span id=status>CONNECTING</span></span></header>
<section class=lcd><div class=tags><span data-u=V class=tag>V</span><span data-u=Ω class=tag>Ω</span><span data-u=F class=tag>F</span><span data-u=Hz class=tag>Hz</span><span data-u=% class=tag>%</span><span id=diode class=tag>DIODE</span><span id=continuity class=tag>CONT</span><span class=sep></span><span id=dc class=tag>DC</span><span id=ac class=tag>AC</span></div>
<div class=read><span id=number class=number>—</span><span id=unit class=unit></span></div><div class="tags fn"><span id=auto class=tag>AUTO</span><span id=hold class="tag warn">HOLD</span><span id=max class=tag>MAX</span><span id=min class=tag>MIN</span></div></section>
<div class=chart><span id=hi class="y t"></span><span id=lo class="y b"></span><svg viewBox="0 0 100 100" preserveAspectRatio=none><polyline id=line points=""/></svg><div class=x><span id=span>—</span><span>now</span></div></div>
<div class=stats><div>MIN<b id=smin>—</b></div><div>MAX<b id=smax>—</b></div><div>AVG<b id=savg>—</b></div><div>SAMPLES<b id=sn>—</b></div></div></main><script>
const $=id=>document.getElementById(id),P={M:1e6,k:1e3,m:1e-3,n:1e-9},MAX=150;let h=[],key='',last=0;
function eng(v,u){if(v==null)return'';let a=Math.abs(v),s=a>=1e6?[1e6,'M']:a>=1e3?[1e3,'k']:a>=1||a===0?[1,'']:a>=1e-3?[1e-3,'m']:a>=1e-6?[1e-6,'µ']:[1e-9,'n'];return +(v/s[0]).toPrecision(4)+' '+s[1]+u}
function stats(v,u){let sum=v.reduce((x,y)=>x+y,0);$('smin').textContent=eng(Math.min(...v),u);$('smax').textContent=eng(Math.max(...v),u);$('savg').textContent=eng(sum/v.length,u);$('sn').textContent=v.length}
function graph(s){if(s.hold)return;let u=s.unit||'',k=u+'|'+(s.mode||'');if(k!==key){key=k;h=[]}
 let v=(s.value==null||!s.unit)?null:s.value*(P[s.prefix]||1);h.push([Date.now(),v]);if(h.length>MAX)h.shift();
 let vs=h.map(p=>p[1]).filter(x=>x!=null);if(!vs.length){$('line').setAttribute('points','');$('hi').textContent=$('lo').textContent=$('span').textContent='';return}
 let a=Math.min(...vs),b=Math.max(...vs);if(a===b){a-=Math.abs(a)*.05||1;b+=Math.abs(b)*.05||1}
 let t0=h[0][0],dt=Math.max(1,Date.now()-t0),seg=[],pts=[];
 h.forEach(p=>{if(p[1]!=null)pts.push(((p[0]-t0)*100/dt).toFixed(2)+','+(95-(p[1]-a)*90/(b-a)).toFixed(2))});
 $('line').setAttribute('points',pts.join(' '));stats(vs,u);$('hi').textContent=eng(b,u);$('lo').textContent=eng(a,u);$('span').textContent='-'+Math.round(dt/1000)+' s'}
function show(s){last=Date.now();let n=$('number');n.className='number'+(s.ol?' ol':'');n.textContent=s.display??(s.ol?'OL':'—');
 let u=$('unit');if(s.unit){u.className='unit';u.textContent=(s.prefix||'')+s.unit}else{u.className='unit q';u.textContent=s.prefix?s.prefix+' ?':''}
 ['ac','dc','auto','hold','max','min','diode','continuity'].forEach(k=>$(k).classList.toggle('on',s[k]===true));let sp=s.diode||s.continuity;document.querySelectorAll('[data-u]').forEach(e=>e.classList.toggle('on',!sp&&e.dataset.u===s.unit));graph(s)}
function go(){let w=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host+'/ws');
 w.onopen=()=>{$('dot').className='dot on';$('status').textContent='LIVE'};w.onmessage=e=>{let s=JSON.parse(e.data);if(s.status)return;show(s)};
 w.onclose=()=>{$('dot').className='dot';$('status').textContent='RECONNECTING';$('number').classList.add('stale');setTimeout(go,1000)}}go();
</script></body></html>)HTML";

void selectMux(int ch){for(int b=0;b<4;b++)digitalWrite(ADDR[b],(ch>>b)&1);} int readSettled(int pin){analogReadMilliVolts(pin);return analogReadMilliVolts(pin);} bool fail(const char*w,int p){errorReason=w;errorPhase=p;return false;}
int band(int mv){int best=0;for(int k=1;k<4;k++)if(fabsf(mv-centers[k])<fabsf(mv-centers[best]))best=k;return fabsf(mv-centers[best])<=tolerance[best]?best:-1;}
bool calibrate(){memset(hist,0,sizeof(hist));for(int i=0;i<4096;i++){int v=readSettled(COM_PIN);hist[min(255,max(0,v/16))]++;if(!(i&255))yield();}int lo=0,hi=255;uint32_t n=0;for(;lo<255;lo++){n+=hist[lo];if(n>=41)break;}n=0;for(;hi>0;hi--){n+=hist[hi];if(n>=41)break;}if(hi-lo<100)return fail("calibration_no_four_bands",-1);for(int k=0;k<4;k++)centers[k]=16*(lo+(hi-lo)*k/3.0f)+8;for(int it=0;it<20;it++){double sum[4]={};uint32_t count[4]={};for(int b=0;b<256;b++){int k=0;float v=16*b+8;for(int j=1;j<4;j++)if(fabsf(v-centers[j])<fabsf(v-centers[k]))k=j;sum[k]+=v*hist[b];count[k]+=hist[b];}for(int k=0;k<4;k++){if(count[k]<200)return fail("calibration_missing_band",-1);centers[k]=sum[k]/count[k];}}for(int k=0;k<4;k++){float gap=4000;if(k)gap=min(gap,centers[k]-centers[k-1]);if(k<3)gap=min(gap,centers[k+1]-centers[k]);if(gap<500)return fail("calibration_overlapping_bands",-1);tolerance[k]=min(200.0f,gap*.20f);}calId++;return true;}
bool nextEdge(int old,int expected,Edge&e,uint32_t initialOld,int phase){uint32_t start=micros(),lastOld=initialOld,firstHi=0;int candidate=-2,count=0,lastMv=0;while(uint32_t(micros()-start)<25000){uint32_t t=micros();int mv=analogReadMilliVolts(COM_PIN);uint32_t end=micros();int b=band(mv);if(b==old){lastOld=t;candidate=-2;count=0;continue;}if(b<0){candidate=-2;count=0;continue;}if(candidate==b)count++;else{candidate=b;count=1;firstHi=end;}lastMv=mv;if(count>=2){if(b!=expected)return fail("phase_sequence",phase);if(uint32_t(firstHi-lastOld)>300)return fail("edge_uncertainty",phase);e={lastOld,firstHi,lastMv};return true;}}return fail("phase_timeout",phase);}
bool startEdge(Edge&e){uint32_t start=micros(),last=0,first=0;int count=0;readSettled(COM_PIN);while(uint32_t(micros()-start)<45000){uint32_t t=micros();int mv=analogReadMilliVolts(COM_PIN);uint32_t end=micros();int b=band(mv);if(b>0){last=t;count=0;}else if(b==0&&last){if(count++==0)first=end;if(count>=2){if(uint32_t(first-last)>300)return fail("sync_edge_uncertainty",0);e={last,first,mv};return true;}}else count=0;}return fail("sync_timeout",0);}
bool capture(){if(!startEdge(f.edge[0]))return false;for(int p=0;p<8;p++){while(uint32_t(micros()-f.edge[p].hi)<60){}f.begin[p]=micros();for(int s=0;s<N;s++){selectMux(s);delayMicroseconds(12);f.mv[p][s]=readSettled(SEG_PIN);}f.end[p]=micros();uint32_t old=micros();f.com[p]=readSettled(COM_PIN);f.post[p]=micros();if(band(f.com[p])!=EXPECTED[p])return fail("scan_crossed_edge",p);if(!nextEdge(EXPECTED[p],EXPECTED[(p+1)%8],f.edge[p+1],old,p))return false;if(uint32_t(f.begin[p]-f.edge[p].hi)<60||int32_t(f.edge[p+1].lo-f.post[p])<60)return fail("phase_guard",p);uint32_t dt=f.edge[p+1].hi-f.edge[p].hi;if(dt<1500||dt>2600)return fail("phase_duration",p);}uint32_t period=f.edge[8].hi-f.edge[0].hi;return period>=14000&&period<=19000?true:fail("frame_duration",8);}

bool matrix(String &out){char b[61];int q=0;for(int s=0;s<15;s++)for(int c=0;c<4;c++){int energy=0;for(int p=0;p<8;p++){int lv=band(f.mv[p][s]);if(lv<0)return false;int d=lv-COMS[c][p];energy+=d*d;}if(energy==8)b[q++]='1';else if(energy==24)b[q++]='0';else return false;}b[60]=0;out=String(b);return true;}
int digit(const String&m,int pos){static const uint8_t cell[4][7]={{40,41,42,43,46,44,45},{32,33,34,35,38,36,37},{20,21,22,23,30,28,29},{16,17,18,19,26,24,25}};static const uint8_t pat[10]={0x3f,0x06,0x5b,0x4f,0x66,0x6d,0x7d,0x07,0x7f,0x6f};uint8_t lit=0;for(int x=0;x<7;x++)if(m[cell[pos][x]]=='0')lit|=1<<x;if(pos==0){uint8_t swapped=(lit&~0x09)|((lit&0x01)?0x08:0)|((lit&0x08)?0x01:0);int d1=-1,d2=-1;for(int d=0;d<10;d++){if(pat[d]==lit)d1=d;if(pat[d]==swapped)d2=d;}return d1==d2?d1:-1;}for(int d=0;d<10;d++)if(pat[d]==lit)return d;return -1;}
String number(const String&m,double &value){String x="";for(int p=0;p<4;p++){int d=digit(m,p);if(d<0)return "";x+=(char)('0'+d);if(p<3&&m[p==0?39:p==1?31:27]=='0')x+='.';}if(x.indexOf('.')>=0)value=x.toDouble();else value=x.toDouble();return x;}
bool lit(const String&m,int i){return m[i]=='0';} String idFor(const String&m){uint32_t h=2166136261u;for(size_t i=0;i<m.length();i++){h^=m[i];h*=16777619u;}char o[9];snprintf(o,sizeof(o),"%08lx",(unsigned long)h);return String(o);}
uint8_t litBits(const String&m,int pos){static const uint8_t cell[4][7]={{40,41,42,43,46,44,45},{32,33,34,35,38,36,37},{20,21,22,23,30,28,29},{16,17,18,19,26,24,25}};uint8_t b=0;for(int x=0;x<7;x++)if(m[cell[pos][x]]=='0')b|=1<<x;return b;}
bool isOL(const String&m){return litBits(m,0)==0&&litBits(m,1)==0x3f&&litBits(m,2)==0x38&&litBits(m,3)==0;} /* "0" then "L"; decimal point position varies by mode */
String jb(bool v){return v?"true":"false";} String js(const String&v){return v.length()?"\""+v+"\"":"null";}
String normalize(const String&m){bool ol=isOL(m);double v=0;String display=ol?"":number(m,v);bool negative=lit(m,50);if(display.length()&&negative){display="-"+display;v=-v;}bool diode=lit(m,53),cont=lit(m,54);String unit=lit(m,1)?"Hz":lit(m,9)?"%":lit(m,3)?"V":lit(m,6)?"\xCE\xA9":lit(m,7)?"F":"";String prefix="";if(lit(m,13))prefix="M";else if(lit(m,10))prefix="k";else if(lit(m,11)||lit(m,15))prefix="m";else if(lit(m,14))prefix="n";String mode=diode?"diode":cont?"continuity":lit(m,51)?"AC":lit(m,49)?"DC":"";String shown=ol?"OL":display;bool hasValue=!ol&&display.length();return "{\"raw_state_id\":\""+idFor(m)+"\",\"display\":"+js(shown)+",\"value\":"+(hasValue?String(v,6):"null")+",\"negative\":"+jb(negative)+",\"unit\":"+js(unit)+",\"prefix\":"+js(prefix)+",\"mode\":"+js(mode)+",\"ac\":"+jb(lit(m,51))+",\"dc\":"+jb(lit(m,49))+",\"auto\":"+jb(lit(m,52))+",\"hold\":"+jb(lit(m,55))+",\"max\":"+jb(lit(m,59))+",\"min\":"+jb(lit(m,58))+",\"ol\":"+jb(ol)+",\"continuity\":"+jb(cont)+",\"diode\":"+jb(diode)+"}";}
void broadcast(const String&s){lastStateJson=s;for(int&i:wsClients)if(i>=0){httpd_ws_frame_t fr={};fr.type=HTTPD_WS_TYPE_TEXT;fr.payload=(uint8_t*)s.c_str();fr.len=s.length();if(httpd_ws_send_frame_async(server,i,&fr)!=ESP_OK)i=-1;}}
esp_err_t root(httpd_req_t*r){httpd_resp_set_type(r,"text/html");httpd_resp_set_hdr(r,"Cache-Control","no-store, max-age=0");httpd_resp_send_chunk(r,PAGE,HTTPD_RESP_USE_STRLEN);return httpd_resp_send_chunk(r,nullptr,0);}esp_err_t ws(httpd_req_t*r){if(r->method==HTTP_GET){for(int&i:wsClients)if(i<0){i=httpd_req_to_sockfd(r);break;}httpd_ws_frame_t fr={};fr.type=HTTPD_WS_TYPE_TEXT;fr.payload=(uint8_t*)lastStateJson.c_str();fr.len=lastStateJson.length();return httpd_ws_send_frame(r,&fr);}return ESP_OK;}
void startWeb(){httpd_config_t cfg=HTTPD_DEFAULT_CONFIG();cfg.max_open_sockets=7;if(httpd_start(&server,&cfg)!=ESP_OK)return;httpd_uri_t a={.uri="/",.method=HTTP_GET,.handler=root,.user_ctx=nullptr,.is_websocket=false};httpd_uri_t b={.uri="/ws",.method=HTTP_GET,.handler=ws,.user_ctx=nullptr,.is_websocket=true};httpd_register_uri_handler(server,&a);httpd_register_uri_handler(server,&b);}
void connectWifi(){WiFi.mode(WIFI_STA);WiFi.begin(METER_WIFI_SSID,METER_WIFI_PASSWORD);uint32_t began=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-began<20000)delay(250);if(WiFi.status()==WL_CONNECTED){MDNS.begin("meter");startWeb();Serial.printf("dashboard http://meter.local/  http://%s/\n",WiFi.localIP().toString().c_str());}else Serial.println("Wi-Fi unavailable; check secrets.h and reboot.");}
void setup(){pinMode(COM_PIN,INPUT);pinMode(SEG_PIN,INPUT);pinMode(PROBE_PIN,INPUT);for(int b=0;b<4;b++){digitalWrite(ADDR[b],LOW);pinMode(ADDR[b],OUTPUT);}analogReadResolution(12);analogSetPinAttenuation(COM_PIN,ADC_11db);analogSetPinAttenuation(SEG_PIN,ADC_11db);analogSetPinAttenuation(PROBE_PIN,ADC_11db);Serial.begin(115200);delay(300);Serial.println("meter dashboard boot");connectWifi();}
void loop(){if(!calibrated)calibrated=calibrate();if(calibrated){seq++;String m;vTaskSuspendAll();bool valid=capture()&&matrix(m);xTaskResumeAll();if(valid){if(m==candidate)candidateCount++;else{candidate=m;candidateCount=1;}if(candidateCount>=3&&m!=lastPublished){lastPublished=m;broadcast(normalize(m));}}else{candidate="";candidateCount=0;}}if(millis()-lastStatus>5000){lastStatus=millis();Serial.printf("wifi=%d ip=%s calibrated=%d error=%s\\n",WiFi.status(),WiFi.localIP().toString().c_str(),calibrated,errorReason);}delay(60);}
