/* Crenova MS8233D reader: Stage 3 self-hosted Wi-Fi dashboard.
 * Acquisition timing and COM profile are retained from accepted Stage 1.
 * The browser receives normalized states only -- never SEG/COM cells.
 */
#include <Arduino.h>
#include <WiFi.h>
#include <ESPmDNS.h>
#include <esp_http_server.h>
#include "secrets.h"

constexpr int COM_PIN=D0, SEG_PIN=D1, PROBE_PIN=D2;
constexpr int ADDR[4]={D3,D6,D7,D8}; constexpr int N=15;
constexpr uint8_t EXPECTED[8]={0,3,2,1,2,1,2,1};
constexpr uint8_t COMS[4][8]={{0,3,2,1,2,1,2,1},{2,1,0,3,2,1,2,1},{2,1,2,1,0,3,2,1},{2,1,2,1,2,1,0,3}};
float centers[4], tolerance[4]; uint32_t hist[256], calId=0,seq=0,lastStatus=0; bool calibrated=false;
const char *errorReason="none"; int errorPhase=-1;
struct Edge{uint32_t lo,hi;int mv;}; struct Frame{Edge edge[9];uint32_t begin[8],end[8],post[8];uint16_t mv[8][N],com[8];} f;

httpd_handle_t server=nullptr; int wsClients[4]={-1,-1,-1,-1};
String lastPublished, candidate; uint8_t candidateCount=0; String lastStateJson="{\"status\":\"starting\"}";

const char PAGE[] PROGMEM=R"HTML(<!doctype html><html><head><meta name=viewport content="width=device-width,initial-scale=1"><title>MS8233D</title><style>
*{box-sizing:border-box}body{margin:0;background:#111714;color:#e6f4eb;font:16px system-ui,sans-serif}.panel{max-width:880px;margin:auto;min-height:100vh;padding:20px;background:linear-gradient(140deg,#1a2620,#101512)}header{display:flex;justify-content:space-between;letter-spacing:.12em;color:#9fbaa9;font-size:.75rem}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:#7e8b82;margin-right:6px}.on{background:#59db86;box-shadow:0 0 10px #59db86}.readout{margin:12vh 0 1rem;text-align:center}.number{font:clamp(4rem,17vw,10rem) ui-monospace,monospace;letter-spacing:-.08em;line-height:1;color:#d8ffd6}.unit{min-height:2rem;font-size:clamp(1.4rem,5vw,3rem);color:#84d999}.flags{display:flex;justify-content:center;flex-wrap:wrap;gap:.55rem;margin:2rem 0}.flag{border:1px solid #405247;border-radius:99px;padding:.35rem .75rem;color:#728278}.flag.active{border-color:#73e298;color:#caffd4;background:#1b3a27}.flag.unknown{display:none}.chart{height:96px;border-top:1px solid #34463b;position:relative;overflow:hidden}.chart svg{width:100%;height:100%;stroke:#64db8b;fill:none;stroke-width:2}.note{text-align:center;color:#829087;font-size:.8rem;margin-top:1rem}</style></head><body><main class=panel><header><span>CRENOVA · MS8233D</span><span><i id=dot class=dot></i><span id=status>CONNECTING</span></span></header><section class=readout><div id=number class=number>—</div><div id=unit class=unit></div></section><section class=flags><span id=ac class=flag>AC</span><span id=dc class=flag>DC</span><span id=auto class=flag>AUTO</span><span id=hold class=flag>HOLD</span><span id=max class=flag>MAX</span><span id=min class=flag>MIN</span><span id=ol class=flag>OL</span><span id=continuity class=flag>CONTINUITY</span><span id=diode class=flag>DIODE</span></section><div class=chart><svg viewBox="0 0 100 100" preserveAspectRatio=none><polyline id=line points=""/></svg></div><div id=note class=note>Waiting for a stable LCD state…</div></main><script>
let h=[];const $=id=>document.getElementById(id);function set(id,v){$(id).classList.toggle('active',v===true);$(id).classList.toggle('unknown',v==null)}function draw(v){if(typeof v!='number'||!isFinite(v))return;h.push(v);if(h.length>50)h.shift();let a=Math.min(...h),b=Math.max(...h),d=b-a||1;$('line').setAttribute('points',h.map((x,i)=>`${i*100/(Math.max(1,h.length-1))},${100-(x-a)*90/d-5}`).join(' '))}function show(s){$('number').textContent=s.display??(s.ol?'OL':'—');$('unit').textContent=[s.prefix,s.unit].filter(Boolean).join('');['ac','dc','auto','hold','max','min','ol','continuity','diode'].forEach(k=>set(k,s[k]));$('note').textContent=s.raw_state_id?'state '+s.raw_state_id:'No decoded state';draw(s.value)}function go(){let p=location.protocol==='https:'?'wss':'ws',w=new WebSocket(p+'://'+location.host+'/ws');w.onopen=()=>{$('dot').className='dot on';$('status').textContent='LIVE'};w.onmessage=e=>show(JSON.parse(e.data));w.onclose=()=>{$('dot').className='dot';$('status').textContent='RECONNECTING';setTimeout(go,1000)}}go();</script></body></html>)HTML";

const char PAGE_PATCH[] PROGMEM=R"HTML(<style>
.chart{height:118px!important;overflow:visible!important;padding:12px 0 18px 38px!important}.chart svg{width:100%;height:100%;stroke:#64db8b;fill:none}.chart polyline{stroke-width:2!important;vector-effect:non-scaling-stroke;stroke-linejoin:round;stroke-linecap:round}.axis-y{position:absolute;left:0;color:#829087;font-size:.68rem}.axis-y.top{top:12px}.axis-y.bottom{bottom:21px}.axis-x{position:absolute;left:38px;right:0;bottom:1px;display:flex;justify-content:space-between;color:#829087;font-size:.68rem}
</style><script>
const chart=document.querySelector('.chart');chart.insertAdjacentHTML('afterbegin','<span id=high class="axis-y top">—</span><span id=low class="axis-y bottom">—</span>');chart.insertAdjacentHTML('beforeend','<div class=axis-x><span>older</span><span>latest</span></div>');draw=function(v){if(typeof v!='number'||!isFinite(v))return;h.push(v);if(h.length>50)h.shift();let a=Math.min(...h),b=Math.max(...h),d=b-a||1;$('high').textContent=b.toPrecision(4);$('low').textContent=a.toPrecision(4);$('line').setAttribute('points',h.map((x,i)=>`${i*100/(Math.max(1,h.length-1))},${100-(x-a)*90/d-5}`).join(' '))};show=function(s){$('number').textContent=s.display??(s.ol?'OL':'—');$('unit').textContent=s.unit?[s.prefix,s.unit].filter(Boolean).join(''):s.prefix?s.prefix+' · unit unknown':'';['ac','dc','auto','hold','max','min','ol','continuity','diode'].forEach(k=>set(k,s[k]));$('note').textContent=s.raw_state_id?'state '+s.raw_state_id:'No decoded state';draw(s.value)};
</script>)HTML";

void selectMux(int ch){for(int b=0;b<4;b++)digitalWrite(ADDR[b],(ch>>b)&1);} int readSettled(int pin){analogReadMilliVolts(pin);return analogReadMilliVolts(pin);} bool fail(const char*w,int p){errorReason=w;errorPhase=p;return false;}
int band(int mv){int best=0;for(int k=1;k<4;k++)if(fabsf(mv-centers[k])<fabsf(mv-centers[best]))best=k;return fabsf(mv-centers[best])<=tolerance[best]?best:-1;}
bool calibrate(){memset(hist,0,sizeof(hist));for(int i=0;i<4096;i++){int v=readSettled(COM_PIN);hist[min(255,max(0,v/16))]++;if(!(i&255))yield();}int lo=0,hi=255;uint32_t n=0;for(;lo<255;lo++){n+=hist[lo];if(n>=41)break;}n=0;for(;hi>0;hi--){n+=hist[hi];if(n>=41)break;}if(hi-lo<100)return fail("calibration_no_four_bands",-1);for(int k=0;k<4;k++)centers[k]=16*(lo+(hi-lo)*k/3.0f)+8;for(int it=0;it<20;it++){double sum[4]={};uint32_t count[4]={};for(int b=0;b<256;b++){int k=0;float v=16*b+8;for(int j=1;j<4;j++)if(fabsf(v-centers[j])<fabsf(v-centers[k]))k=j;sum[k]+=v*hist[b];count[k]+=hist[b];}for(int k=0;k<4;k++){if(count[k]<200)return fail("calibration_missing_band",-1);centers[k]=sum[k]/count[k];}}for(int k=0;k<4;k++){float gap=4000;if(k)gap=min(gap,centers[k]-centers[k-1]);if(k<3)gap=min(gap,centers[k+1]-centers[k]);if(gap<500)return fail("calibration_overlapping_bands",-1);tolerance[k]=min(200.0f,gap*.20f);}calId++;return true;}
bool nextEdge(int old,int expected,Edge&e,uint32_t initialOld,int phase){uint32_t start=micros(),lastOld=initialOld,firstHi=0;int candidate=-2,count=0,lastMv=0;while(uint32_t(micros()-start)<25000){uint32_t t=micros();int mv=analogReadMilliVolts(COM_PIN);uint32_t end=micros();int b=band(mv);if(b==old){lastOld=t;candidate=-2;count=0;continue;}if(b<0){candidate=-2;count=0;continue;}if(candidate==b)count++;else{candidate=b;count=1;firstHi=end;}lastMv=mv;if(count>=2){if(b!=expected)return fail("phase_sequence",phase);if(uint32_t(firstHi-lastOld)>300)return fail("edge_uncertainty",phase);e={lastOld,firstHi,lastMv};return true;}}return fail("phase_timeout",phase);}
bool startEdge(Edge&e){uint32_t start=micros(),last=0,first=0;int count=0;readSettled(COM_PIN);while(uint32_t(micros()-start)<45000){uint32_t t=micros();int mv=analogReadMilliVolts(COM_PIN);uint32_t end=micros();int b=band(mv);if(b>0){last=t;count=0;}else if(b==0&&last){if(count++==0)first=end;if(count>=2){if(uint32_t(first-last)>300)return fail("sync_edge_uncertainty",0);e={last,first,mv};return true;}}else count=0;}return fail("sync_timeout",0);}
bool capture(){if(!startEdge(f.edge[0]))return false;for(int p=0;p<8;p++){while(uint32_t(micros()-f.edge[p].hi)<60){}f.begin[p]=micros();for(int s=0;s<N;s++){selectMux(s);delayMicroseconds(12);f.mv[p][s]=readSettled(SEG_PIN);}f.end[p]=micros();uint32_t old=micros();f.com[p]=readSettled(COM_PIN);f.post[p]=micros();if(band(f.com[p])!=EXPECTED[p])return fail("scan_crossed_edge",p);if(!nextEdge(EXPECTED[p],EXPECTED[(p+1)%8],f.edge[p+1],old,p))return false;if(uint32_t(f.begin[p]-f.edge[p].hi)<60||int32_t(f.edge[p+1].lo-f.post[p])<60)return fail("phase_guard",p);uint32_t dt=f.edge[p+1].hi-f.edge[p].hi;if(dt<1500||dt>2600)return fail("phase_duration",p);}uint32_t period=f.edge[8].hi-f.edge[0].hi;return period>=14000&&period<=19000?true:fail("frame_duration",8);}

bool matrix(String &out){char b[61];int q=0;for(int s=0;s<15;s++)for(int c=0;c<4;c++){int energy=0;for(int p=0;p<8;p++){int lv=band(f.mv[p][s]);if(lv<0)return false;int d=lv-COMS[c][p];energy+=d*d;}if(energy==8)b[q++]='1';else if(energy==24)b[q++]='0';else return false;}b[60]=0;out=String(b);return true;}
int digit(const String&m,int pos){static const uint8_t cell[4][7]={{40,41,42,43,46,44,45},{32,33,34,35,38,36,37},{20,21,22,23,30,28,29},{16,17,18,19,26,24,25}};static const uint8_t pat[10]={0x3f,0x06,0x5b,0x4f,0x66,0x6d,0x7d,0x07,0x7f,0x6f};uint8_t lit=0;for(int x=0;x<7;x++)if(m[cell[pos][x]]=='0')lit|=1<<x;if(pos==0){uint8_t swapped=(lit&~0x09)|((lit&0x01)?0x08:0)|((lit&0x08)?0x01:0);int d1=-1,d2=-1;for(int d=0;d<10;d++){if(pat[d]==lit)d1=d;if(pat[d]==swapped)d2=d;}return d1==d2?d1:-1;}for(int d=0;d<10;d++)if(pat[d]==lit)return d;return -1;}
String number(const String&m,double &value){String x="";for(int p=0;p<4;p++){int d=digit(m,p);if(d<0)return "";x+=(char)('0'+d);if(p<3&&m[p==0?39:p==1?31:27]=='0')x+='.';}if(x.indexOf('.')>=0)value=x.toDouble();else value=x.toDouble();return x;}
bool lit(const String&m,int i){return m[i]=='0';} String idFor(const String&m){uint32_t h=2166136261u;for(size_t i=0;i<m.length();i++){h^=m[i];h*=16777619u;}char o[9];snprintf(o,sizeof(o),"%08lx",(unsigned long)h);return String(o);}
uint8_t litBits(const String&m,int pos){static const uint8_t cell[4][7]={{40,41,42,43,46,44,45},{32,33,34,35,38,36,37},{20,21,22,23,30,28,29},{16,17,18,19,26,24,25}};uint8_t b=0;for(int x=0;x<7;x++)if(m[cell[pos][x]]=='0')b|=1<<x;return b;}
bool isOL(const String&m){return litBits(m,0)==0&&litBits(m,1)==0x3f&&litBits(m,2)==0x38&&litBits(m,3)==0;} /* "0" then "L"; decimal point position varies by mode */
String jb(bool v){return v?"true":"false";} String js(const String&v){return v.length()?"\""+v+"\"":"null";}
String normalize(const String&m){bool ol=isOL(m);double v=0;String display=ol?"":number(m,v);bool negative=lit(m,50);if(display.length()&&negative){display="-"+display;v=-v;}bool diode=lit(m,53),cont=lit(m,54);String unit=lit(m,1)?"Hz":lit(m,9)?"%":lit(m,3)?"V":lit(m,6)?"\xCE\xA9":lit(m,7)?"F":"";String prefix="";if(lit(m,13))prefix="M";else if(lit(m,10))prefix="k";else if(lit(m,11)||lit(m,15))prefix="m";else if(lit(m,14))prefix="n";String mode=diode?"diode":cont?"continuity":lit(m,51)?"AC":lit(m,49)?"DC":"";String shown=ol?"OL":display;bool hasValue=!ol&&display.length();return "{\"raw_state_id\":\""+idFor(m)+"\",\"display\":"+js(shown)+",\"value\":"+(hasValue?String(v,6):"null")+",\"negative\":"+jb(negative)+",\"unit\":"+js(unit)+",\"prefix\":"+js(prefix)+",\"mode\":"+js(mode)+",\"ac\":"+jb(lit(m,51))+",\"dc\":"+jb(lit(m,49))+",\"auto\":"+jb(lit(m,52))+",\"hold\":"+jb(lit(m,55))+",\"max\":"+jb(lit(m,59))+",\"min\":"+jb(lit(m,58))+",\"ol\":"+jb(ol)+",\"continuity\":"+jb(cont)+",\"diode\":"+jb(diode)+"}";}
void broadcast(const String&s){lastStateJson=s;for(int&i:wsClients)if(i>=0){httpd_ws_frame_t fr={};fr.type=HTTPD_WS_TYPE_TEXT;fr.payload=(uint8_t*)s.c_str();fr.len=s.length();if(httpd_ws_send_frame_async(server,i,&fr)!=ESP_OK)i=-1;}}
esp_err_t root(httpd_req_t*r){httpd_resp_set_type(r,"text/html");httpd_resp_set_hdr(r,"Cache-Control","no-store, max-age=0");httpd_resp_send_chunk(r,PAGE,HTTPD_RESP_USE_STRLEN);httpd_resp_send_chunk(r,PAGE_PATCH,HTTPD_RESP_USE_STRLEN);return httpd_resp_send_chunk(r,nullptr,0);}esp_err_t ws(httpd_req_t*r){if(r->method==HTTP_GET){for(int&i:wsClients)if(i<0){i=httpd_req_to_sockfd(r);break;}httpd_ws_frame_t fr={};fr.type=HTTPD_WS_TYPE_TEXT;fr.payload=(uint8_t*)lastStateJson.c_str();fr.len=lastStateJson.length();return httpd_ws_send_frame(r,&fr);}return ESP_OK;}
void startWeb(){httpd_config_t cfg=HTTPD_DEFAULT_CONFIG();cfg.max_open_sockets=7;if(httpd_start(&server,&cfg)!=ESP_OK)return;httpd_uri_t a={.uri="/",.method=HTTP_GET,.handler=root,.user_ctx=nullptr,.is_websocket=false};httpd_uri_t b={.uri="/ws",.method=HTTP_GET,.handler=ws,.user_ctx=nullptr,.is_websocket=true};httpd_register_uri_handler(server,&a);httpd_register_uri_handler(server,&b);}
void connectWifi(){WiFi.mode(WIFI_STA);WiFi.begin(METER_WIFI_SSID,METER_WIFI_PASSWORD);uint32_t began=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-began<20000)delay(250);if(WiFi.status()==WL_CONNECTED){MDNS.begin("meter");startWeb();Serial.printf("dashboard http://meter.local/  http://%s/\n",WiFi.localIP().toString().c_str());}else Serial.println("Wi-Fi unavailable; check secrets.h and reboot.");}
void setup(){pinMode(COM_PIN,INPUT);pinMode(SEG_PIN,INPUT);pinMode(PROBE_PIN,INPUT);for(int b=0;b<4;b++){digitalWrite(ADDR[b],LOW);pinMode(ADDR[b],OUTPUT);}analogReadResolution(12);analogSetPinAttenuation(COM_PIN,ADC_11db);analogSetPinAttenuation(SEG_PIN,ADC_11db);analogSetPinAttenuation(PROBE_PIN,ADC_11db);Serial.begin(115200);delay(300);Serial.println("meter dashboard boot");connectWifi();}
void loop(){if(!calibrated)calibrated=calibrate();if(calibrated){seq++;String m;vTaskSuspendAll();bool valid=capture()&&matrix(m);xTaskResumeAll();if(valid){if(m==candidate)candidateCount++;else{candidate=m;candidateCount=1;}if(candidateCount>=3&&m!=lastPublished){lastPublished=m;broadcast(normalize(m));}}else{candidate="";candidateCount=0;}}if(millis()-lastStatus>5000){lastStatus=millis();Serial.printf("wifi=%d ip=%s calibrated=%d error=%s\\n",WiFi.status(),WiFi.localIP().toString().c_str(),calibrated,errorReason);}delay(60);}
